theme: jekyll-theme-minimal
title: Project Portfolio
description: Hi there! This page contains a non-exhaustive list of my previous/ongoing projects with a bunch of links to give more information to the projects. 
